overrides:
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  ejs@<3.1.10: '>=3.1.10'
  ejs@<3.1.7: '>=3.1.7'
  form-data@<2.5.4: '>=2.5.4'
  http-proxy-middleware@<2.0.7: '>=2.0.7'
  http-proxy-middleware@>=1.3.0 <2.0.8: '>=2.0.8'
  http-proxy-middleware@>=1.3.0 <2.0.9: '>=2.0.9'
  json5@<1.0.2: '>=1.0.2'
  loader-utils@<1.4.1: '>=1.4.1'
  micromatch@<4.0.8: '>=4.0.8'
  node-forge@<1.0.0: '>=1.0.0'
  node-forge@<1.3.0: '>=1.3.0'
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  vue-template-compiler@>=2.0.0 <3.0.0: '>=3.0.0'
  vue@>=2.0.0-alpha.1 <3.0.0-alpha.0: '>=2.7.16'
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
